title: Kenneth KOFFI
tagline: Administrateur systèmes et réseaux | enthousiaste du Cloud et du DevOps
description: "Tout ce qui n'est pas écrit, est oublié"
cover: /jonathan-SwVkmowt7qA-unsplash.jpg

categories_path: /categories/
tags_path: /tags/
